name = "picoforge"
productName = "picoforge"
description = "An open source commissioning tool for Pico FIDO security keys. Developed with Rust and GPUI."
category = "Utility"
version = "0.4.0"
authors = ["Suyog Tandel", "PicoForge Contributers"]
identifier = "in.suyogtandel.picoforge"
license_file = "LICENSE"

icons = [
    "./static/appIcons/in.suyogtandel.picoforge.svg",
    "./static/appIcons/icon.png",
    "./static/appIcons/icon.ico",
    "./static/appIcons/icon.icns",
    "./static/appIcons/32x32.png",
    "./static/appIcons/64x64.png",
    "./static/appIcons/128x128.png",
    "./static/appIcons/128x128@2x.png",
    "./static/appIcons/Square30x30Logo.png",
    "./static/appIcons/Square44x44Logo.png",
    "./static/appIcons/Square71x71Logo.png",
    "./static/appIcons/Square89x89Logo.png",
    "./static/appIcons/Square107x107Logo.png",
    "./static/appIcons/Square142x142Logo.png",
    "./static/appIcons/Square150x150Logo.png",
    "./static/appIcons/Square284x284Logo.png",
    "./static/appIcons/Square310x310Logo.png",
    "./static/appIcons/StoreLogo.png",
]

# beforePackagingCommand = "cargo build --release"

binaries = [{ main = true, name = "picoforge" }]
# outDir = "packaging/cargoPackager"

[linux]
generateDesktopEntry = false

[appimage]
excludedLibs = ["libpcsclite*.so*"]
files = { "data/in.suyogtandel.picoforge.desktop" = "usr/share/applications/in.suyogtandel.picoforge.desktop", "static/appIcons/in.suyogtandel.picoforge-symbolic.svg" = "usr/share/icons/hicolor/symbolic/apps/in.suyogtandel.picoforge-symbolic.svg", "static/appIcons/in.suyogtandel.picoforge.svg" = "usr/share/icons/hicolor/scalable/apps/in.suyogtandel.picoforge.svg" }

# NOTE: The paths for .deb packages needs to be verified not sure about these.
[deb]
files = { "data/in.suyogtandel.picoforge.desktop" = "usr/share/applications/in.suyogtandel.picoforge.desktop", "static/appIcons/in.suyogtandel.picoforge-symbolic.svg" = "usr/share/icons/hicolor/symbolic/apps/in.suyogtandel.picoforge-symbolic.svg", "static/appIcons/in.suyogtandel.picoforge.svg" = "usr/share/icons/hicolor/scalable/apps/in.suyogtandel.picoforge.svg" }
